-------------------------------------------------------------------------------
--
-- Music Rev band setup Lua.
--
-- Gabs
--
-------------------------------------------------------------------------------
--
-- use:
--
-- DrummerPlacementModel   = "c0000_Band_nnnn_xxxx"
--
-- where "c0000_Band_nnnn_xxxx" is the model referenced in the scene xml
-- to be replaced in the game by the appropriate character model
--
-- same with Vocals, Guitar and Bass.
--
-------------------------------------------------------------------------------

UsingDefaultCharacterModelPlacementScript = false

DrummerPlacementModel   = "c0000_0001_drummer_0000"
GuitaristPlacementModel = "c0000_0002_guitarist_0000"
BassistPlacementModel   = "c0000_0003_bassist_0000"
VocalistPlacementModel  = "c0000_0004_vocalist_0000"
