-------------------------------------------------------------------------------
--
-- Music Rev incidental character setup.
--
-- Gabs
--
-- incidental characters and their anims
--
-------------------------------------------------------------------------------
--
-- Incidental characters are specified as
--
-- model to look for in the scene:
--
-- IncidentalCharacter_00_Model = "modelname"
--
-------------------------------------------------------------------------------
--
-- animations to play if youre doing badly, ok (or idle), or brilliantly
-- these can be set to "" if not used, idle should always be set if there's
-- a model specified:
--
-- IncidentalCharacter_00_AnimDisgusted = ""
-- IncidentalCharacter_00_AnimIdle = ""
-- IncidentalCharacter_00_AnimExcited = ""
--
-------------------------------------------------------------------------------

IncidentalCharacter_00_Model = "c0007_0001_Bassist_body"
IncidentalCharacter_00_AnimDisgusted = ""
IncidentalCharacter_00_AnimIdle = "c0007_1004_slow"
IncidentalCharacter_00_AnimExcited = ""

IncidentalCharacter_01_Model = "c0005_Drummer_body"
IncidentalCharacter_01_AnimDisgusted = ""
IncidentalCharacter_01_AnimIdle = "c0005_0002_drumming"
IncidentalCharacter_01_AnimExcited = ""

IncidentalCharacter_02_Model = "c0006_0001_Guitarist_body"
IncidentalCharacter_02_AnimDisgusted = ""
IncidentalCharacter_02_AnimIdle = "c0006_1003_strumFlat"
IncidentalCharacter_02_AnimExcited = ""

IncidentalCharacter_03_Model = "c0004_0001_Vocalist_body"
IncidentalCharacter_03_AnimDisgusted = ""
IncidentalCharacter_03_AnimIdle = "c0004_1005_standingIdle"
IncidentalCharacter_03_AnimExcited = ""

IncidentalCharacter_04_Model = "c0005_0005"
IncidentalCharacter_04_AnimDisgusted = ""
IncidentalCharacter_04_AnimIdle = "c0005_0002_drumming"
IncidentalCharacter_04_AnimExcited = ""

IncidentalCharacter_05_Model = "c0005_0006"
IncidentalCharacter_05_AnimDisgusted = ""
IncidentalCharacter_05_AnimIdle = "c0005_0003_sittingIdle"
IncidentalCharacter_05_AnimExcited = ""

IncidentalCharacter_06_Model = "c0005_0007"
IncidentalCharacter_06_AnimDisgusted = ""
IncidentalCharacter_06_AnimIdle = "c0005_0004_clickSticks"
IncidentalCharacter_06_AnimExcited = ""

IncidentalCharacter_07_Model = "c0005_0008"
IncidentalCharacter_07_AnimDisgusted = ""
IncidentalCharacter_07_AnimIdle = "c0005_0005_standingIdle"
IncidentalCharacter_07_AnimExcited = ""


