Chord00000 =
{
	Up = { 000, "OpenHarm_u", ""},
	Down = { 000, "OpenHarm_d", ""},
	TiltUp = { 084, "OpenHarm_u", ""},
	TiltDown = { 084, "OpenHarm_d", ""},
}

Chord10000 = 
{
	Up = { 004, "Chrd_Emin_u", "Emin"},
	Down = { 004, "Chrd_Emin_d", "Emin"},
	TiltUp = { 088, "Note_E1_u", "E"},
	TiltDown = { 088, "Note_E1_d", "E"},
}

Chord01000 = 
{
	Up = { 007, "Chrd_G_u", "G"},
	Down = { 007, "Chrd_G_d", "G"},
	TiltUp = { 091, "Note_G1_u", "G"},
	TiltDown = { 091, "Note_G1_d", "G"},
}

Chord00100 = 
{
	Up = { 009, "Chrd_Amin_u", "Amin"},
	Down = { 009, "Chrd_Amin_d", "Amin"},
	TiltUp = { 093, "Note_A1_u", "A"},
	TiltDown = { 093, "Note_A1_d", "A"},
}

Chord00010 = 
{
	Up = { 012, "Chrd_C_u", "C"},
	Down = { 012, "Chrd_C_d", "C"},
	TiltUp = { 096, "Note_C2_u", "C"},
	TiltDown = { 096, "Note_C2_d", "C"},
}

Chord00001 = 
{
	Up = { 014, "Chrd_D_u", "D"},
	Down = { 014, "Chrd_D_d", "D"},
	TiltUp = { 098, "Note_D2_u", "D"},
	TiltDown = { 098, "Note_D2_d", "D"},
}

Chord11000 = 
{
	Up = { 005, "Chrd_F_u", "F"},
	Down = { 005, "Chrd_F_d", "F"},
	TiltUp = { 089, "Note_F1_u", "F"},
	TiltDown = { 089, "Note_F1_d", "F"},
}

Chord01100 = 
{
	Up = { 008, "Chrd_G#min7_u", "G#min7"},
	Down = { 008, "Chrd_G#min7_d", "G#min7"},
	TiltUp = { 092, "Note_G#1_u", "G#"},
	TiltDown = { 092, "Note_G#1_d", "G#"},
}

Chord00110 = 
{
	Up = { 022, "Chrd_Bb_u", "A#"},
	Down = { 022, "Chrd_Bb_d", "A#"},
	TiltUp = { 094, "Note_A#1_u", "A#"},
	TiltDown = { 094, "Note_A#1_d", "A#"},
}

Chord00011 = 
{
	Up = { 013, "Chrd_C#min7_u", "C#min7"},
	Down = { 013, "Chrd_C#min7_d", "C#min7"},
	TiltUp = { 097, "Note_C#2_u", "C#"},
	TiltDown = { 097, "Note_C#2_d", "C#"},
}

Chord10100 = 
{
	Up = { 006, "Chrd_D-F#_u", "D/F#"},
	Down = { 006, "Chrd_D-F#_d", "D/F#"},
	TiltUp = { 090, "Note_F#1_u", "F#"},
	TiltDown = { 090, "Note_F#1_d", "F#"},
}

Chord01010 = 
{
	Up = { 023, "Chrd_Bmin11_u", "Bmin11"},
	Down = { 023, "Chrd_Bmin11_d", "Bmin11"},
	TiltUp = { 095, "Note_B1_u", "B"},
	TiltDown = { 095, "Note_B1_d", "B"},
}

Chord00101 = 
{
	Up = { 011, "Chrd_B_u", "B"},
	Down = { 011, "Chrd_B_d", "B"},
	TiltUp = { 099, "Note_D#2_u", "D#"},
	TiltDown = { 099, "Note_D#2_d", "D#"},
}

Chord11100 = 
{
	Up = { 016, "Chrd_Emin7_u", "Emin7"},
	Down = 	{ 016, "Chrd_Emin7_d", "Emin7"},
	TiltUp = { 100, "Note_E2_u", "E"},
	TiltDown = { 100, "Note_E2_d", "E"},
}

Chord01110 = 
{
	Up = { 019, "Chrd_G7_u", "G7"},
	Down = { 019, "Chrd_G7_d", "G7"},
	TiltUp = { 103, "Note_G2_u", "G"},
	TiltDown = { 103, "Note_G2_d", "G"},
}

Chord00111 = 
{
	Up = { 033, "Chrd_Amin7_u", "Amin7"},
	Down = { 033, "Chrd_Amin7_d", "Amin7"},
	TiltUp = { 105, "Note_A2_u", "A"},
	TiltDown = { 105, "Note_A2_d", "A"},
}

Chord10010 = 
{
	Up = { 018, "Chrd_F#min7_u", "F#min7"},
	Down = { 018, "Chrd_F#min7_d", "F#min7"},
	TiltUp = { 102, "Note_F#2_u", "F#"},
	TiltDown = { 102, "Note_F#2_d", "F#"},
}

Chord01001 = 
{
	Up = { 035, "Chrd_B-E_u", "B/E"},
	Down = { 035, "Chrd_B-E_d", "B/E"},
	TiltUp = { 107, "Note_B2_u", "B"},
	TiltDown = { 107, "Note_B2_d", "B"},
}

Chord11110 = 
{
	Up = { 036, "Chrd_Cmaj7_u", "Cmaj7"},
	Down = { 036, "Chrd_Cmaj7_d", "Cmaj7"},
	TiltUp = { 108, "Note_C3_u", "C"},
	TiltDown = { 108, "Note_C3_d", "C"},
}

Chord01111 = 
{
	Up = { 038, "Chrd_D7_u", "D7"},
	Down = { 038, "Chrd_D7_d", "D7"},
	TiltUp = { 110, "Note_D3_u", "D"},
	TiltDown = { 110, "Note_D3_d", "D"},
}

Chord11010 = 
{
	Up = { 081, "Chrd_Fmaj7-A_u", "Fmaj7/A"},
	Down = { 081, "Chrd_Fmaj7-A_d", "Fmaj7/A"},
	TiltUp = { 101, "Note_F2_u", "F"},
	TiltDown = { 101, "Note_F2_d", "F"},
}

Chord10110 = 
{
	Up = { 021, "Chrd_Asus4_u", "Asus4"},
	Down = { 021, "Chrd_Asus4_d", "Asus4"},
	TiltUp = { 106, "Note_A#2_u", "A#"},
	TiltDown = { 106, "Note_A#2_d", "A#"},
}

Chord01101 = 
{
	Up = { 024, "Chrd_Cadd9_u", "Cadd9"},
	Down = { 024, "Chrd_Cadd9_d", "Cadd9"},
	TiltUp = { 104, "Note_G#2_u", "G#"},
	TiltDown = { 104, "Note_G#2_d", "G#"},
}

Chord01011 = 
{
	Up = { 026, "Chrd_Dsus4_u", "Dsus4"},
	Down = { 026, "Chrd_Dsus4_d", "Dsus4"},
	TiltUp = { 109, "Note_C#3_u", "C#"},
	TiltDown = { 109, "Note_C#3_d", "C#"},
}

Chord10001 = 
{
	Up = { 045, "Chrd_Asus2_u", "Asus2"},
	Down = { 045, "Chrd_Asus2_d", "Asus2"},
	TiltUp = { 111, "Note_D#3_u", "D#"},
	TiltDown = { 111, "Note_D#3_d", "D#"},
}

Chord11001 = 
{
	Up = { 050, "Chrd_Dsus2_u", "Dsus2"},
	Down = { 050, "Chrd_Dsus2_d", "Dsus2"},
	TiltUp = { 116, "Note_G#3_u", "G#"},
	TiltDown = { 116, "Note_G#3_d", "G#"},
}

Chord10011 = 
{
	Up = { 062, "Chrd_Dmin_u", "Dmin"},
	Down = { 062, "Chrd_Dmin_d", "Dmin"},
	TiltUp = { 113, "Note_F3_u", "F"},
	TiltDown = { 113, "Note_F3_d", "F"},
}

Chord11101 = 
{
	Up = { 028, "Chrd_E_u", "E"},
	Down = { 028, "Chrd_E_d", "E"},
	TiltUp = { 114, "Note_F#3_u", "F#"},
	TiltDown = { 114, "Note_F#3_d", "F#"},
}

Chord10111 = 
{
	Up = { 057, "Chrd_A_u", "A"},
	Down = { 057, "Chrd_A_d", "A"},
	TiltUp = { 115, "Note_G3_u", "G"},
	TiltDown = { 115, "Note_G3_d", "G"},
}

Chord10101 = 
{
	Up = { 040, "Chrd_E7_u", "E7"},
	Down = 	{ 040, "Chrd_E7_d", "E7"},
	TiltUp = { 112, "Note_E3_u", "E"},
	TiltDown = { 112, "Note_E3_d", "E"},
}

Chord11011 = 
{ 
	Up = { 069, "Chrd_A-E_u", "A/E"},
	Down = 	{ 069, "Chrd_A-E_d", "A/E"},
	TiltUp = { 117, "Note_A3_u", "A"},
	TiltDown = { 117, "Note_A3_d", "A"},
}

Chord11111 = 
{
	Up = { 074, "Chrd_Dmin7_u", "Dmin7"},
	Down = { 074, "Chrd_Dmin7_d", "Dmin7"},
	TiltUp = { 118, "Note_A#3_u", "A#"},
	TiltDown = { 118, "Note_A#3_d", "A#"},
}
