Chord00000 =
{
	Up = 	{ 000, "Strum_u", ""},
    	Down = 	{ 000, "Strum_d", ""},
 	TiltUp = { 084, "Strum_u", ""},
    	TiltDown = { 084, "Strum_d", ""},
}

Chord10000 = 
{
	Up = 	{ 004, "PChrd_E1_u", "E"},
	Down = 	{ 004, "PChrd_E1_d", "E"},
 	TiltUp = { 088, "Slide_E2", "E"},
    	TiltDown = { 088, "Solo_E2", "E"},
}

Chord01000 = 
{
	Up = 	{ 007, "PChrd_G1_u", "G"},
	Down = 	{ 007, "PChrd_G1_d", "G"},
 	TiltUp = { 091, "Slide_G2", "G"},
    	TiltDown = { 091, "Solo_G2", "G"},
}

Chord00100 = 
{
	Up = 	{ 009, "PChrd_A1_u", "A"},
	Down = 	{ 009, "PChrd_A1_d", "A"},
 	TiltUp = { 093, "Slide_A2", "A"},
    	TiltDown = { 093, "Solo_A2", "A"},
}

Chord00010 = 
{
	Up = 	{ 012, "PChrd_C2_u", "C"},
	Down = 	{ 012, "PChrd_C2_d", "C"},
 	TiltUp = { 096, "Slide_C3", "C"},
    	TiltDown = { 096, "Solo_C3", "C"},
}

Chord00001 = 
{
	Up = 	{ 014, "PChrd_D2_u", "D"},
	Down = 	{ 014, "PChrd_D2_d", "D"},
 	TiltUp = { 098, "Slide_D3", "D"},
    	TiltDown = { 098, "Solo_D3", "D"},
}

Chord11000 = 
{
	Up = 	{ 005, "PChrd_F1_u", "F"},
	Down = 	{ 005, "PChrd_F1_d", "F"},
 	TiltUp = { 089, "Slide_F2", "F"},
    	TiltDown = { 089, "Solo_F2", "F"},
}

Chord01100 = 
{
	Up = 	{ 008, "PChrd_G#1_u", "G#"},
	Down = 	{ 008, "PChrd_G#1_d", "G#"},
 	TiltUp = { 092, "Slide_G#2", "G#"},
    	TiltDown = { 092, "Solo_G#2", "G#"},
}

Chord00110 = 
{
	Up = 	{ 010, "PChrd_A#1_u", "A#"},
	Down = 	{ 010, "PChrd_A#1_d", "A#"},
 	TiltUp = { 094, "Slide_A#2", "A#"},
    	TiltDown = { 094, "Solo_A#2", "A#"},
}

Chord00011 = 
{
	Up = 	{ 013, "PChrd_C#2_u", "C#"},
	Down = 	{ 013, "PChrd_C#2_d", "C#"},
 	TiltUp = { 097, "Slide_C#3", "C#"},
    	TiltDown = { 097, "Solo_C#3", "C#"},
}

Chord10100 = 
{
	Up = 	{ 006, "PChrd_F#1_u", "F#"},
	Down = 	{ 006, "PChrd_F#1_d", "F#"},
 	TiltUp = { 090, "Slide_F#2", "F#"},
    	TiltDown = { 090, "Solo_F#2", "F#"},
}

Chord01010 = 
{
	Up = 	{ 011, "PChrd_B1_u", "B"},
	Down = 	{ 011, "PChrd_B1_d", "B"},
 	TiltUp = { 095, "Slide_B2", "B"},
    	TiltDown = { 095, "Solo_B2", "B"},
}

Chord00101 = 
{
	Up = 	{ 015, "PChrd_D#2_u", "D#"},
	Down = 	{ 015, "PChrd_D#2_d", "D#"},
 	TiltUp = { 099, "Slide_D#3", "D#"},
    	TiltDown = { 099, "Solo_D#3", "D#"},
}

Chord11100 = 
{
	Up = 	{ 016, "PChrd_E2_u", "E"},
  	Down = 	{ 016, "PChrd_E2_d", "E"},
 	TiltUp = { 100, "Slide_E3", "E"},
    	TiltDown = { 100, "Solo_E3", "E"},
}

Chord01110 = 
{
	Up = 	{ 019, "PChrd_G2_u", "G"},
  	Down = 	{ 019, "PChrd_G2_d", "G"},
 	TiltUp = { 103, "Slide_G3", "G"},
    	TiltDown = { 103, "Solo_G3", "G"},
}

Chord00111 = 
{
	Up = 	{ 021, "PChrd_A2_u", "A"},
  	Down = 	{ 021, "PChrd_A2_d", "A"},
 	TiltUp = { 105, "Slide_A3", "A"},
    	TiltDown = { 105, "Solo_A3", "A"},
}

Chord10010 = 
{
	Up = 	{ 018, "PChrd_F#2_u", "F#"},
	Down = 	{ 018, "PChrd_F#2_d", "F#"},
 	TiltUp = { 102, "Slide_F#3", "F#"},
    	TiltDown = { 102, "Solo_F#3", "F#"},
}

Chord01001 = 
{
	Up = 	{ 023, "PChrd_B2_u", "B"},
	Down = 	{ 023, "PChrd_B2_d", "B"},
 	TiltUp = { 107, "Slide_B3", "B"},
    	TiltDown = { 107, "Solo_B3", "B"},
}

Chord11110 = 
{
	Up = 	{ 024, "PChrd_C3_u", "C"},
	Down = 	{ 024, "PChrd_C3_d", "C"},
 	TiltUp = { 108, "Slide_C4", "C"},
    	TiltDown = { 108, "Solo_C4", "C"},
}

Chord01111 = 
{
	Up = 	{ 026, "PChrd_D3_u", "D"},
	Down = 	{ 026, "PChrd_D3_d", "D"},
 	TiltUp = { 110, "Slide_D4", "D"},
    	TiltDown = { 110, "Solo_D4", "D"},
}

Chord11010 = 
{
	Up = 	{ 017, "PChrd_F2_u", "F"},
  	Down = 	{ 017, "PChrd_F2_d", "F"},
 	TiltUp = { 101, "Slide_F3", "F"},
    	TiltDown = { 101, "Solo_F3", "F"},
}

Chord10110 = 
{
	Up = 	{ 022, "PChrd_A#2_u", "A#"},
	Down = 	{ 022, "PChrd_A#2_d", "A#"},
 	TiltUp = { 106, "Slide_A#3", "A#"},
    	TiltDown = { 106, "Solo_A#3", "A#"},
}

Chord01101 = 
{
	Up = 	{ 020, "PChrd_G#2_u", "G#"},
	Down = 	{ 020, "PChrd_G#2_d", "G#"},
 	TiltUp = { 104, "Slide_G#3", "G#"},
    	TiltDown = { 104, "Solo_G#3", "G#"},
}

Chord01011 = 
{
	Up = 	{ 025, "PChrd_C#3_u", "C#"},
	Down = 	{ 025, "PChrd_C#3_d", "C#"},
 	TiltUp = { 109, "Slide_C#4", "C#"},
    	TiltDown = { 109, "Solo_C#4", "C#"},
}

Chord10001 = 
{
	Up = 	{ 027, "PChrd_D#3_u", "D#"},
	Down = 	{ 027, "PChrd_D#3_d", "D#"},
 	TiltUp = { 111, "Slide_D#4", "D#"},
    	TiltDown = { 111, "Solo_D#4", "D#"},
}

Chord11001 = 
{
	Up = 	{ 031, "Chrd_G7#9_u", "G7#9"},
	Down = 	{ 031, "Chrd_G7#9_d", "G7#9"},
 	TiltUp = { 043, "Chrd_G7#9_u", "G7#9"},
    	TiltDown = { 043, "Chrd_G7#9_d", "G7#9"},
}

Chord10011 = 
{
	Up = 	{ 038, "Chrd_D7#9_u", "D7#9"},
	Down = 	{ 038, "Chrd_D7#9_d", "D7#9"},
 	TiltUp = { 050, "Chrd_D7#9_u", "D7#9"},
    	TiltDown = { 050, "Chrd_D7#9_d", "D7#9"},
}

Chord11101 = 
{
	Up = 	{ 045, "Chrd_A7#9_u", "A7#9"},
	Down = 	{ 045, "Chrd_A7#9_d", "A7#9"},
 	TiltUp = { 057, "Chrd_A7#9_u", "A7#9"},
    	TiltDown = { 057, "Chrd_A7#9_d", "A7#9"},
}

Chord10111 = 
{
	Up = 	{ 035, "Chrd_B7#9_u", "B7#9"},
	Down = 	{ 035, "Chrd_B7#9_d", "B7#9"},
 	TiltUp = { 047, "Chrd_B7#9_u", "B7#9"},
    	TiltDown = { 047, "Chrd_B7#9_d", "B7#9"},
}

Chord10101 = 
{
	Up = 	{ 028, "PChrd_E3_u", "E"},
	Down = 	{ 028, "PChrd_E3_d", "E"},
 	TiltUp = { 112, "Slide_E4", "E"},
    	TiltDown = { 112, "Solo_E4", "E"},
}

Chord11011 = 
{
	Up = 	{ 040, "Chrd_E7#9_u", "E7#9"},
	Down = 	{ 040, "Chrd_E7#9_d", "E7#9"},
 	TiltUp = { 052, "Chrd_E7#9_u", "E7#9"},
    	TiltDown = { 052, "Chrd_E7#9_d", "E7#9"},
}

Chord11111 = 
{
	Up = 	{ 064, "Chrd_E7#5_u", "E7#5"},
	Down = 	{ 064, "Chrd_E7#5_d", "E7#5"},
 	TiltUp = { 076, "Chrd_E7#5_u", "E7#5"},
    	TiltDown = { 076, "Chrd_E7#5_d", "E7#5"},
}