-------------------------------------------------------------------------------
--
-- Drum Rev Signal Rule Action List
--
-- Gabs
--
-------------------------------------------------------------------------------
-- Drummer, both sexes and all songs
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
-- Signal Rule Action list
-------------------------------------------------------------------------------

Playing = 0
MidiNote = 0

SourceDrummerAnimationMidi = 2

-------------------------------------------------------------------------------

DrumsSignalRuleActions =
{

	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 21,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_24_RD_Loop_Half"
	},
	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 23,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_44_HH_Loop_Half"
	},
	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 22,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_34_HH_Loop_Half"
	},
	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 18,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_LRBarr_Loop_Half"
	},
	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 19,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_SnareFill_Loop_Half"
	},
	
	
	
	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 2,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_CrashR_Half_01"
	},
	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 3,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_CrashR_Half_02"
	},
	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 4,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_CrashL_Half_03"
	},
	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 5,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_CrashL_Half_04"
	},
	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 6,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_CrashR_Half_05"
	},
	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 7,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_CrashR_Half_06"
	},
	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 8,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_CrashL_Half_07"
	},
	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 9,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_CrashL_Half_08"
	},
	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 10,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_CrashR_Half_09"
	},
	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 11,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_CrashR_Half_10"
	},
	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 12,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_CrashL_Half_11"
	},
	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 13,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_CrashL_Half_12"
	},
	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 14,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_CrashR_Half_13"
	},
	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 15,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_CrashR_Half_14"
	},
	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 16,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_CrashL_Half_15"
	},
	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 17,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_CrashL_Half_16"
	},
	
	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 115,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_SnareFlam_Loop_Half_01"
	},
	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 116,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_SnareFlam_Loop_Half_02"
	},
	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 117,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_SnareFlam_Loop_Half_03"
	},
	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 118,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_SnareFlam_Loop_Half_04"
	},
	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 119,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_SnareFlam_Loop_Half_05"
	},
	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 120,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_SnareFlam_Loop_Half_06"
	},
	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 121,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_SnareFlam_Loop_Half_07"
	},
	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 122,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_SnareFlam_Loop_Half_08"
	},
	
	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 43,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_24Cut_Loop_Half"
	},
	
	
	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 76,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_LRFill_Loop_Half_01"
	},
	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 77,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_LRFill_Loop_Half_02"
	},
	
	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 114,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_CountIn_Half"
	},
	
	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 36,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_24_RD_Loop_02"
	},
	
	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 80,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_Tribal_Loop_Half"
	},
	
	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 124,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_NoPlay_Half"
	},
	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 28,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_24_HH_Loop_Half"
	},
	
	
	
	
	
	
	
	
	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 108,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_Idle"
	},
	
	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 107,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_Idle_02"
	},

	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 109,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_NoPlay"
	},

	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 112,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_CountIn"
	},

	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 20,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_16Hihat_Loop_02"
	},

	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 24,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_16Hihat_Loop"
	},

	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 25,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_16Hihat_Cymbal"
	},

	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 26,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_16Hihat_Snare_Cymbal"
	},

	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 27,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_16Hihat_Snare_Loop"
	},

	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 31,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_24_HH_Loop_02"
	},

	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 32,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_24_HH_Cymbal"
	},

	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 33,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_24_HH_Loop"
	},

	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 34,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_24_RD_Cymbal"
	},

	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 35,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_24_RD_Loop"
	},

	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 40,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_24Cut_Cymbal"
	},

	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 41,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_24Cut_Loop"
	},

	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 42,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_24Cut_Loop_02"
	},

	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 44,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_34_HH_Cymbal"
	},

	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 45,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_34_HH_Loop"
	},

	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 46,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_34_RD_Cymbal"
	},

	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 47,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_34_RD_Loop"
	},
	
	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 48,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_34_HH_Cymbal_02"
	},

	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 49,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_34_HH_Loop_02"
	},

	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 50,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_34_RD_Cymbal_02"
	},

	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 51,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_34_RD_Loop_02"
	},

	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 52,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_44_HH_Cymbal"
	},

	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 53,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_44_HH_Loop"
	},

	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 56,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_44_HH_Loop_02"
	},

	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 54,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_44_RD_Cymbal"
	},

	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 55,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_44_RD_Loop"
	},

	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 60,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_DoubleStop_Cymbal"
	},

	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 63,--Already in use?!?!?!?? ("...DoubleStop_Loop_04")

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_DoubleStop_Cymbal_02"--Wolfmother
	},

	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 61,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_DoubleStop_Loop"
	},
	
	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 62,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_DoubleStop_Loop_02"--SPOONMAN
	},
	
	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 63,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_DoubleStop_Loop_03"--Crescendo to barline
	},
	
	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 59,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_DoubleStop_Loop_04"--Half Speed
	},
	
	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 0,

		RulePriority = 64,
		RulePlayer = Playing,
		--Play Looping
		ActionPlayAnimation = "Drummer_DoubleStop_Loop_HIT_01"--double speed
	},

	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 64,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_LRBarr_Cymbal"
	},

	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 65,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_LRBarr_Loop"
	},

	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 1,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_LRBarr_Loop_HIT_01"
	},

	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 58,--was 62 before spoonman trip toms correction (not sure if this will mess up with any drum anim, it wasn't documented in spreadsheet so shouldn't be used anywhere)

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_LRBarr_Loop_02"
	},

	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 66,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_LRFill_Cymbal"
	},

	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 67,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_LRFill_Loop"
	},

	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 68,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_LRFill_Loop_02"
	},

	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 70,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_SnareFill_Cymbal"
	},

	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 71,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_SnareFill_Loop"
	},

	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 72,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_SnareFill_Loop_02"
	},

	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 74,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_SnareFlam_Cymbal"
	},

	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 75,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_SnareFlam_Loop"
	},

	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 85,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_SnareFlam_Loop_02"
	},

	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 86,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_SnareFlam_Loop_03"
	},

	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 87,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_SnareFlam_Loop_04"
	},

	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 78,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_Tribal_Cymbal"
	},

	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 79,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_Tribal_Loop"
	},

	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 82,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_TripToms_Cymbal_F"
	},

	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 81,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_TripToms_Cymbal_M"
	},

	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 83,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_TripToms_Loop"
	},

	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 96,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_CrashL"
	},
	
	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 95,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_CrashL_02"
	},
	
	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 94,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_CrashL_03"
	},
	
	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 93,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_CrashL_04"
	},

	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 92,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_CrashL_05"
	},
	
	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 91,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_CrashL_06"
	},
	
	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 90,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_CrashL_07"
	},
	
	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 89,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_CrashL_08"
	},
	
	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 88,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_CrashL_09"
	},
	
	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 84,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_CrashL_10"
	},
	
	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 97,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_CrashR"
	},
		
	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 98,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_CrashR_02"
	},	
	
	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 99,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_CrashR_03"
	},
		
	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 100,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_CrashR_04"
	},
		
	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 101,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_CrashR_05"
	},
		
	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 102,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_CrashR_06"
	},
		
	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 103,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_CrashR_07"
	},
		
	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 104,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_CrashR_08"
	},
		
	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 105,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_CrashR_09"
	},
		
	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 106,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_CrashR_10"
	},
		
	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 110,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_CrashR_11"
	},
		
	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 111,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_CrashR_12"
	},
	
	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 113,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_CrashR_13"
	},
	
	{
		SignalSource = SourceDrummerAnimationMidi,
		SignalType = MidiNote,
		SignalNote = 127,

		RulePriority = 64,
		RulePlayer = Playing,

		ActionPlayAnimation = "Drummer_CymbalSwell"
	},
}

--FilterMenu = {}
--for i,line in fe do
--	FilterMenu[i] = line;
--end
