NumTriggersUsed = 7

TriggerMap01 = 
{
	Trigger.kFloorTom,				
	4,					
	Keyboard.kNum3,			
	GuitarInput.kFret4,
	MidiInput.k5,
	XenonPad.kX,
	"FloorTom",
}

TriggerMap02 = 
{
	Trigger.kRackTom,				
	4,					
	Keyboard.kNum3,			
	GuitarInput.kFret4,
	MidiInput.k5,
	XenonPad.kX,
	"RackTom",
}

TriggerMap03 = 
{
	Trigger.kKickDrum,				
	3,					
	Keyboard.kNum1,			
	GuitarInput.kSelect,
	MidiInput.k7,
	XenonPad.kL,
	"KickDrum",
}

TriggerMap04 = 
{
	Trigger.kSnare,			
	1,					
	Keyboard.kNum6,			
	GuitarInput.kFret2,
	MidiInput.k1,
	XenonPad.kB,
	"Snare",
}

TriggerMap05 = 
{
	Trigger.kCrash,				
	5,					
	Keyboard.kNum2,			
	GuitarInput.kFret1,
	MidiInput.k4,
	XenonPad.kA,
	"Crash",
}

TriggerMap06 = 
{
	Trigger.kRide,				
	5,					
	Keyboard.kNum2,			
	GuitarInput.kFret1,
	MidiInput.k4,
	XenonPad.kA,
	"Ride",
}

TriggerMap07 = 
{
	Trigger.kHiHat,				
	2,					
	Keyboard.kNum5,			
	GuitarInput.kFret3,
	MidiInput.k2,
	XenonPad.kY,
	"HiHat",
}