NumTriggersUsed = 5

TriggerMap01 = 
{
	Trigger.kFret1,			
	1,					
	Keyboard.kNum1,			
	GuitarInput.kFret1,
	MidiInput.k1,
	XenonPad.kA,
	"Fret1",
}

TriggerMap02 = 
{
	Trigger.kFret2,			
	2,					
	Keyboard.kNum2,			
	GuitarInput.kFret2,
	MidiInput.k2,
	XenonPad.kB,
	"Fret2",
}

TriggerMap03 = 
{
	Trigger.kFret3,				
	3,					
	Keyboard.kNum3,			
	GuitarInput.kFret3,
	MidiInput.k3,
	XenonPad.kY,
	"Fret3",
}

TriggerMap04 = 
{
	Trigger.kFret4,				
	4,					
	Keyboard.kNum4,			
	GuitarInput.kFret4,
	MidiInput.k4,
	XenonPad.kX,
	"Fret4",
}

TriggerMap05 = 
{
	Trigger.kFret5,				
	5,					
	Keyboard.kNum5,			
	GuitarInput.kFret5,
	MidiInput.k5,
	XenonPad.kL,
	"Fret5",
}
