Misc =
{
	FadeInRate = 1.0
}

-- Sizes of fonts
FontSize =
{
	GameMode		 = 84;
	SongName		 = 36;
	ResultCard		 = 24;
	WinningCondition = 75;
	ScoringFactor	 = 36;
	Message			 = 30;
	Options			 = 30;
	BigTab			 = 60;
	SmallTab		 = 18;
	OnlineVsPlace	 = 30;
	OnlineVsResult	 = 30;
}

FontName = 
{
	Normal 			= DrumFont.kDefault;
	WinningCondition= DrumFont.kBoycott;
	GameMode		= DrumFont.kBoycott;
	SongName		= DrumFont.kDefault;
}

Colours =
{
	TitleColour 	= DrumColour.kTitle,
	LabelColour 	= DrumColour.kBody,
	HighlightColour = DrumColour.kSelection
}

-- These define texture and the area inside the texture where text can safely be displayed
TextureGroup = "@app:Data/Common/common_0004"
LayoutInfo = 
{	
	GenericInfoMask = 
	{		
		TextureName 	= "common_0004_resultsGenericInfoMask_d",
		TextTopLeft 	= { 50, 60 },	
		TextAreaSize 	= { 520.0, 260.0 }
	},
	
	LargeTab1 = 
	{		
		TextureName		= "common_0004_resultsLargeTab1_d",
		TextTopLeft 	= { 20, 10 },	
		TextAreaSize	= { 228, 56 }
	},
	
	LargeTab2 = 
	{		
		TextureName		= "common_0004_resultsLargeTab2_d",
		TextTopLeft 	= { 20, 10 },	
		TextAreaSize	= { 228, 56 }
	},
	
	PlayerHighlightsPlayer1 = 
	{		
		TextureName		= "common_0004_resultsPeripheralIconsQuadrantsTopLeft_d",
		TextTopLeft 	= { 0, 0 },	
		TextAreaSize	= { 0, 0 }
	},
		
	PlayerHighlightsPlayer2 = 
	{		
		TextureName		= "common_0004_resultsPeripheralIconsQuadrantsTopRight_d",
		TextTopLeft 	= { 0, 0 },	
		TextAreaSize	= { 0, 0 }
	},
	
	PlayerHighlightsPlayer3 = 
	{		
		TextureName		= "common_0004_resultsPeripheralIconsQuadrantsBottomLeft_d",
		TextTopLeft 	= { 0, 0 },	
		TextAreaSize	= { 0, 0 }
	},
	
	PlayerHighlightsPlayer4 = 
	{		
		TextureName		= "common_0004_resultsPeripheralIconsQuadrantsBottomRight_d",
		TextTopLeft 	= { 0, 0 },	
		TextAreaSize	= { 0, 0 }
	},
	
	PlayerInstrumentBass = 
	{		
		TextureName		= "common_0004_resultsPlayerInstrumentBass_d",
		TextTopLeft 	= { 0, 0 },	
		TextAreaSize	= { 0, 0 }
	},
	
	PlayerInstrumentcontroller = 
	{		
		TextureName		= "common_0004_resultsPeripheralIconsControllerIcon_d",
		TextTopLeft 	= { 0, 0 },	
		TextAreaSize	= { 0, 0 }
	},
		
	PlayerInstrumentDrum = 
	{		
		TextureName		= "common_0004_resultsPeripheralIconsDrumIcon_d",
		TextTopLeft 	= { 0, 0 },	
		TextAreaSize	= { 0, 0 }
	},
		
	PlayerInstrumentGuitar = 
	{		
		TextureName		= "common_0004_resultsPeripheralIconsGuitarIcon_d",
		TextTopLeft 	= { 0, 0 },	
		TextAreaSize	= { 0, 0 }
	},
		
	PlayerResultMask1 = 
	{		
		TextureName		= "common_0004_resultsPlayerResultMaskOne_d",
		TextTopLeft 	= { 50,50 },	
		TextAreaSize	= { 220, 390 }
	},
		
	PlayerResultMask2 = 
	{		
		TextureName		= "common_0004_resultsPlayerResultMaskTwo_d",
		TextTopLeft 	= { 50,50 },	
		TextAreaSize	= { 220, 390 }
	},
		
	PlayerResultMask3 = 
	{		
		TextureName		= "common_0004_resultsPlayerResultMaskThree_d",
		TextTopLeft 	= { 50,50 },	
		TextAreaSize	= { 220, 390 }
	},
		
	SmallTab1 = 
	{		
		TextureName		= "common_0004_resultsSmallTab1_d",
		TextTopLeft 	= { 24, 24 },	
		TextAreaSize	= { 81, 189 }
	},
		
	SmallTab2 = 
	{		
		TextureName		= "common_0004_resultsSmallTab2_d",
		TextTopLeft 	= { 24, 24 },	
		TextAreaSize	= { 81, 189 }
	},
		
	SmallTab3 = 
	{		
		TextureName		= "common_0004_resultsSmallTab3_d",
		TextTopLeft 	= { 24, 24 },	
		TextAreaSize	= { 81, 189 }
	},
		
	SmallTab4 = 
	{		
		TextureName		= "common_0004_resultsSmallTab4_d",
		TextTopLeft 	= { 24, 24 },	
		TextAreaSize	= { 81, 189 }
	},
		
	SongPerformanceRatingSelected = 
	{		
		TextureName		= "common_0004_resultsSongPerformanceRatingSelected_d",
		TextTopLeft 	= { 0, 0 },	
		TextAreaSize	= { 0, 0 }
	},
		
	SongPerformanceRatingUnSelected = 
	{		
		TextureName		= "common_0004_resultsSongPerformanceRatingUnSelected_d",
		TextTopLeft 	= { 0, 0 },	
		TextAreaSize	= { 0, 0 }
	},
		
	GradientMask = 
	{		
		TextureName		= "common_0004_resultsScreenGradientMask_d",
		TextTopLeft 	= { 0, 0 },	
		TextAreaSize	= { 0, 0 }
	},
		
	ScoreboardMask = 
	{		
		TextureName		= "common_0004_resultsScoreboardMask_d",
		TextTopLeft 	= { 49, 49 },	
		TextAreaSize	= { 450, 396 }
	},
	
	Long = 
	{		
		TextureName		= "common_0004_resultsScreenLong_d",
		TextTopLeft 	= { 50, 115 },	
		TextAreaSize	= { 746, 122 }
	},
	
	LongGig = 
	{		
		TextureName		= "common_0004_resultsScreenLongGig_d",
		TextTopLeft 	= { 50, 85 },	
		TextAreaSize	= { 746, 150 }
	},
}
