-------------------------------------------------------------------------------
--
-- Music Rev default character animation setup Lua.
--
-- for the Male rig
--
-------------------------------------------------------------------------------

-------------------------------------------------------------------------------

--animation, ik (left hand), bone control (right hand), empty flag, empty flag,

DrummerAnimationsMale = 
{
	"c5000_1000", false, 	false, 	true,			true,			false,				true,	true,	true,	0,			0,		0,0,0,
	"c5000_1001", false, 	false, 	true,			true,			false,				true,	true,	true,	0,			0,		0,0,0,
	"c5000_1003", false, 	false, 	true,			true,			false,				true,	true,	true,	0,			0,		0,0,0,
	"c5000_1004", false, 	false, 	true,			true,			false,				true,	true,	true,	0,			0,		0,0,0,
	"c5000_1100", false, 	false, 	true,			true,			false,				true,	true,	true,	0,			0,		0,3,0,
	"c5000_1101", false, 	false, 	true,			true,			false,				true,	true,	true,	0,			0,		0,1,0,	
	"c5000_1102", false, 	false, 	true,			true,			false,				true,	true,	true,	0,			0,		0,2,0,	
	"c5000_1103", false, 	false, 	true,			true,			false,				true,	true,	true,	0,			0,		0,3,0,	
	"c5000_1104", false, 	false, 	true,			true,			false,				true,	true,	true,	0,			0,		0,1,0,	
	"c5000_1105", false, 	false, 	true,			true,			false,				true,	true,	true,	0,			0,		0,2,0,	
	"c5000_1106", false, 	false, 	true,			true,			false,				true,	true,	true,	0,			0,		0,3,0,	
	"c5000_1107", false, 	false, 	true,			true,			false,				true,	true,	true,	0,			0,		0,1,0,	
	"c5000_1108", false, 	false, 	true,			true,			false,				true,	true,	true,	0,			0,		0,2,0,	
	"c5000_1109", false, 	false, 	true,			true,			false,				true,	true,	true,	0,			0,		0,3,0,	
	"c5000_1110", false, 	false, 	true,			true,			false,				true,	true,	true,	0,			0,		0,1,0,	
	"c5000_1111", false, 	false, 	true,			true,			false,				true,	true,	true,	0,			0,		0,2,0,	
	"c5000_1112", false, 	false, 	true,			true,			false,				true,	true,	true,	0,			0,		0,3,0,	
	"c5000_1113", false, 	false, 	true,			true,			false,				true,	true,	true,	0,			0,		0,1,0,
	"c5000_1114", false, 	false, 	true,			true,			false,				true,	true,	true,	0,			0,		0,3,0,	
	"c5000_1115", false, 	false, 	true,			true,			false,				true,	true,	true,	0,			0,		0,1,0,	
	"c5000_1210", false, 	false, 	true,			true,			false,				true,	true,	true,	0,			0,		0,2,0,	
	"c5000_1211", false, 	false, 	true,			true,			false,				true,	true,	true,	0,			0,		0,3,0,	
	"c5000_1212", false, 	false, 	true,			true,			false,				true,	true,	true,	0,			0,		0,1,0,	
	"c5000_1213", false, 	false, 	true,			true,			false,				true,	true,	true,	0,			0,		0,2,0,	
	"c5000_1220", false, 	false, 	true,			true,			false,				true,	true,	true,	0,			0,		0,3,0,	
	"c5000_1221", false, 	false, 	true,			true,			false,				true,	true,	true,	0,			0,		0,1,0,	
	"c5000_1222", false, 	false, 	true,			true,			false,				true,	true,	true,	0,			0,		0,2,0,	
	"c5000_1223", false, 	false, 	true,			true,			false,				true,	true,	true,	0,			0,		0,3,0,	
	"c5000_1230", false, 	false, 	true,			true,			false,				true,	true,	true,	0,			0,		0,1,0,	
	"c5000_1231", false, 	false, 	true,			true,			false,				true,	true,	true,	0,			0,		0,2,0,	
	"c5000_1310", false, 	false, 	true,			true,			false,				true,	true,	true,	0,			0,		0,3,0,	
	"c5000_1311", false, 	false, 	true,			true,			false,				true,	true,	true,	0,			0,		0,1,0,	
	"c5000_1320", false, 	false, 	true,			true,			false,				true,	true,	true,	0,			0,		0,2,0,	
	"c5000_1321", false, 	false, 	true,			true,			false,				true,	true,	true,	0,			0,		0,3,0,	
	"c5000_1410", false, 	false, 	true,			true,			false,				true,	true,	true,	0,			0,		0,1,0,	
	"c5000_1411", false, 	false, 	true,			true,			false,				true,	true,	true,	0,			0,		0,2,0,	
	"c5000_1412", false, 	false, 	true,			true,			false,				true,	true,	true,	0,			0,		0,3,0,	
	"c5000_1413", false, 	false, 	true,			true,			false,				true,	true,	true,	0,			0,		0,1,0,	
	"c5000_1420", false, 	false, 	true,			true,			false,				true,	true,	true,	0,			0,		0,2,0,	
	"c5000_1421", false, 	false, 	true,			true,			false,				true,	true,	true,	0,			0,		0,3,0,	
	"c5000_1422", false, 	false, 	true,			true,			false,				true,	true,	true,	0,			0,		0,1,0,	
	"c5000_1423", false, 	false, 	true,			true,			false,				true,	true,	true,	0,			0,		0,2,0,	
	"c5000_1610", false, 	false, 	true,			true,			false,				true,	true,	true,	0,			0,		0,3,0,	
	"c5000_1611", false, 	false, 	true,			true,			false,				true,	true,	true,	0,			0,		0,1,0,	
	"c5000_1612", false, 	false, 	true,			true,			false,				true,	true,	true,	0,			0,		0,2,0,	
	"c5000_1613", false, 	false, 	true,			true,			false,				true,	true,	true,	0,			0,		0,3,0,	
--		Trucker Specific Animations                                                                                          		
	"c5005_1062", false, 	false, 	false,			false,			false,		  		true,   true,   true,   0,			115,		1,3,0,-- truckerEndHi
--	"c5005_1061", false,    false,  false,           false,           false,              true,   true,   true,   0,          116,		1,3,0, -- truckerEndLo
	"c5005_1500", false,    false,  false,           false,           false,              true,   true,   true,   0,          0,		1,3,0, -- truckerNoPlay
	"c5005_1001", false,    false,  false,           false,           false,              true,   true,   true,   0,          113,		1,3,0, -- truckerShowOff
--              TeenPunk Specific Animations
	"c5006_1062", false, 	false, 	false,			false,			false,		    	true,   true,   true,   0,			115,		1,3,0,-- teenEndHi
	"c5006_1061", false,    false,  false,           false,           false,              true,   true,   true,   0,          116,		1,3,0, -- teenEndLo
	"c5006_1500", false,    false,  false,           false,           false,              true,   true,   true,   0,          0,		1,3,0, -- teenNoPlay
	"c5006_1001", false,    false,  false,           false,           false,              true,   true,   true,   0,          113,		1,3,0, -- teenShowOff
--              Roadie Specific Animations
	"c5010_1062", false, 	false, 	false,			false,			false,		    	true,   true,   true,   0,			115,		1,3,0,-- roadieEndHi
	"c5010_1061", false,    false,  false,           false,           false,              true,   true,   true,   0,          116,		1,3,0, -- roadieEndLo
	"c5010_1500", false,    false,  false,           false,           false,              true,   true,   true,   0,          0,		1,3,0, -- roadieNoPlay
	"c5010_1001", false,    false,  false,           false,           false,              true,   true,   true,   0,          113,		1,3,0, -- roadieShowOff
--              Mohawk Specific Animations
	"c5011_1062", false, 	false, 	false,			false,			false,		    	true,   true,   true,   0,			115,		1,3,0,-- mohawkEndHi
	"c5011_1061", false,    false,  false,           false,           false,              true,   true,   true,   0,          116,		1,3,0, -- mohawkEndLo
	"c5011_1500", false,    false,  false,           false,           false,              true,   true,   true,   0,          0,		1,3,0, -- mohawkNoPlay
--	"c5011_1001", false,    false,  false,           false,           false,              true,   true,   true,   0,          113,		1,3,0, -- mohawkShowOff
--              Retro Specific Animations
	"c5009_1001", false,    false,  false,           false,           false,              true,   true,   true,   0,          113,		1,3,0, -- retroShowOff
--              Double Speed animations
	"c5000_1224", false, 	false, 	true,			true,			false,				true,	true,	true,	0,			0,			0,2,0,  --2/4RDLoop
	"c5000_1414", false, 	false, 	true,			true,			false,				true,	true,	true,	0,			0,			0,2,0,  --4/4HHLoop
	"c5000_1312", false, 	false, 	true,			true,			false,				true,	true,	true,	0,			0,			0,2,0,  --3/4HHLoop
	"c5000_1117", false, 	false, 	true,			true,			false,				true,	true,	true,	0,			0,			0,2,0,  --snareFillLoop
	"c5000_1116", false, 	false, 	true,			true,			false,				true,	true,	true,	0,			0,			0,2,0,  --LRBarrageLoop
	"c5000_1214", false, 	false, 	true,			true,			false,				true,	true,	true,	0,			0,			0,2,0,  --2/4HHLoop
}                 
                  
-------------------------------------------------------------------------------

