-- Rock Revolution Band -- Shes The Bug --

ListInJamMode = false

-- Audio Mastering information
k1062 = 
{	
	ParentMix = "MusicMix001",
	MixType = 2,		
	Volume = 0,	
	DSPs = { "Compressor1062" }
}

Compressor1062 = 
{ 
	MixType = 3,
	EffectType = 17,
	EffectParam001 = { "Threshold", -11.22 },
	EffectParam002 = { "Attack", 63.4 },
	EffectParam003 = { "Release", 94.4 },		 
	EffectParam004 = { "Gain", 5.37 }	
}
