
Constants = Constants or {}

require "FE_Default"
require "FE_RoomScreen"
require "FE_CareerSectionScreen"
require "FE_CareerAlbumScreen"
require "FE_EventSelectScreen"
require "FE_CareerGigScreen"
require "FE_CharacterSelectScreen"
require "FE_MP3Player"
require "FE_KonamiOptionsScreen"
require "FE_PeripheralMappingScreen"
require "FE_CalibrationScreen"
require "FE_OfflineHighScoreScreen"
require "FE_LobbyScreen"
require "FE_CreditsScreen"
require "FE_SPInstrumentSelectScreen"
require "FE_GameOptionsScreen"
AllowTransitionControls = true
