

--Created in MoonApp/Main.cpp...Geo order as from the dae...before it is sorted by Moon



--Load the geos in the order of 

PreSortOrder = 
{
	"h0001_5002_blindFillBottom_p1_0000",
	"h0001_5003_blindFillMiddle_p1_0000",
	"h0001_5004_blindFillTop_p1_0000",
	"h0001_5057_questionMarkMarker_p1_0000",
}
PostSortOrder = 
{
	h0001_5002_blindFillBottom_p1_0000 = { 	 modelIndex = 0, 	 instanceIndex = -1},
	h0001_5003_blindFillMiddle_p1_0000 = { 	 modelIndex = 1, 	 instanceIndex = -1},
	h0001_5004_blindFillTop_p1_0000 = { 	 modelIndex = 2, 	 instanceIndex = -1},
	h0001_5057_questionMarkMarker_p1_0000 = { 	 modelIndex = 3, 	 instanceIndex = -1},
}
