

--Created in MoonApp/Main.cpp...Geo order as from the dae...before it is sorted by Moon



--Load the geos in the order of 

PreSortOrder = 
{
	"h0001_5059_lifeCounterBackground_p1_0000",
	"h0001_5060_lifeCounter_p1_0000",
	"h0001_5060_lifeCounter_p1_0001",
	"h0001_5060_lifeCounter_p1_0002",
	"h0001_5060_lifeCounter_p1_0003",
	"h0001_5060_lifeCounter_p1_0004",
}
PostSortOrder = 
{
	h0001_5059_lifeCounterBackground_p1_0000 = { 	 modelIndex = 0, 	 instanceIndex = -1},
	h0001_5060_lifeCounter_p1_0000 = { 	 modelIndex = 1, 	 instanceIndex = -1},
	h0001_5060_lifeCounter_p1_0001 = { 	 modelIndex = 1, 	 instanceIndex = 0},
	h0001_5060_lifeCounter_p1_0002 = { 	 modelIndex = 1, 	 instanceIndex = 1},
	h0001_5060_lifeCounter_p1_0003 = { 	 modelIndex = 1, 	 instanceIndex = 2},
	h0001_5060_lifeCounter_p1_0004 = { 	 modelIndex = 1, 	 instanceIndex = 3},
}
