

--Created in MoonApp/Main.cpp...Geo order as from the dae...before it is sorted by Moon



--Load the geos in the order of 

PreSortOrder = 
{
	"h0001_5032_atmosBackdrop1_p1_0000",
	"h0001_5045_atmosBackdrop5_p1_0000",
	"h0001_5100_atmosMeter_p1_0000",
	"h0001_5100_atmosMeter_p2_0000",
	"h0001_5022_scoreNumberBot_p2_0006",
	"h0001_5022_scoreNumberBot_p2_0005",
	"h0001_5022_scoreNumberBot_p2_0004",
	"h0001_5022_scoreNumberBot_p2_0003",
	"h0001_5022_scoreNumberBot_p2_0002",
	"h0001_5022_scoreNumberBot_p2_0001",
	"h0001_5022_scoreNumberBot_p2_0000",
	"h0001_5022_scoreNumberBot_p1_0000",
	"h0001_5022_scoreNumberBot_p1_0001",
	"h0001_5022_scoreNumberBot_p1_0002",
	"h0001_5022_scoreNumberBot_p1_0003",
	"h0001_5022_scoreNumberBot_p1_0004",
	"h0001_5022_scoreNumberBot_p1_0005",
	"h0001_5022_scoreNumberBot_p1_0006",
}
PostSortOrder = 
{
	h0001_5022_scoreNumberBot_p2_0006 = { 	 modelIndex = 0, 	 instanceIndex = -1},
	h0001_5022_scoreNumberBot_p2_0005 = { 	 modelIndex = 0, 	 instanceIndex = 0},
	h0001_5022_scoreNumberBot_p2_0004 = { 	 modelIndex = 0, 	 instanceIndex = 1},
	h0001_5022_scoreNumberBot_p2_0003 = { 	 modelIndex = 0, 	 instanceIndex = 2},
	h0001_5022_scoreNumberBot_p2_0002 = { 	 modelIndex = 0, 	 instanceIndex = 3},
	h0001_5022_scoreNumberBot_p2_0001 = { 	 modelIndex = 0, 	 instanceIndex = 4},
	h0001_5022_scoreNumberBot_p2_0000 = { 	 modelIndex = 0, 	 instanceIndex = 5},
	h0001_5022_scoreNumberBot_p1_0000 = { 	 modelIndex = 0, 	 instanceIndex = 6},
	h0001_5022_scoreNumberBot_p1_0001 = { 	 modelIndex = 0, 	 instanceIndex = 7},
	h0001_5022_scoreNumberBot_p1_0002 = { 	 modelIndex = 0, 	 instanceIndex = 8},
	h0001_5022_scoreNumberBot_p1_0003 = { 	 modelIndex = 0, 	 instanceIndex = 9},
	h0001_5022_scoreNumberBot_p1_0004 = { 	 modelIndex = 0, 	 instanceIndex = 10},
	h0001_5022_scoreNumberBot_p1_0005 = { 	 modelIndex = 0, 	 instanceIndex = 11},
	h0001_5022_scoreNumberBot_p1_0006 = { 	 modelIndex = 0, 	 instanceIndex = 12},
	h0001_5032_atmosBackdrop1_p1_0000 = { 	 modelIndex = 1, 	 instanceIndex = -1},
	h0001_5045_atmosBackdrop5_p1_0000 = { 	 modelIndex = 2, 	 instanceIndex = -1},
	h0001_5100_atmosMeter_p1_0000 = { 	 modelIndex = 3, 	 instanceIndex = -1},
	h0001_5100_atmosMeter_p2_0000 = { 	 modelIndex = 3, 	 instanceIndex = 0},
}
