Chord00000 =
{
	Up = 	{ 001, "Scrape_04", ""},
    	Down = 	{ 001, "Scrape_04", ""},
 	TiltUp = { 037, "Scrape_04", ""},
    	TiltDown = { 037, "Scrape_04", ""},
}

Chord10000 = 
{
	Up = 	{ 002, "Slide_root", "E"},
    	Down = 	{ 002, "Vib_root", "E"},
 	TiltUp = { 038, "Slide_root", "E"},
    	TiltDown = { 038, "Vib_root", "E"},
}

Chord01000 = 
{
	Up = 	{ 003, "Slide_third", "G"},
    	Down = 	{ 003, "Vib_third", "G"},
 	TiltUp = { 039, "Slide_third", "G"},
 	TiltDown = { 039, "Vib_third", "G"},
}

Chord00100 = 
{
	Up = 	{ 004, "Slide_fifth", "B"},
    	Down = 	{ 004, "Vib_fifth", "B"},
 	TiltUp = { 040, "Slide_fifth", "B"},
	TiltDown = { 040, "Vib_fifth", "B"},
}

Chord00010 = 
{
	Up = 	{ 005, "Slide_seventh", "D"},
    	Down = 	{ 005, "Vib_seventh", "D"},
 	TiltUp = { 041, "Slide_seventh", "D"},
    	TiltDown = { 041, "Vib_seventh", "D"},
}

Chord00001 = 
{
	Up = 	{ 006, "Slide_octave", "E"},
    	Down = 	{ 006, "Vib_octave", "E"},
 	TiltUp = { 042, "Slide_octave", "E"},
	TiltDown = { 042, "Vib_octave", "E"},
}

Chord11000 = 
{
	Up = 	{ 007, "Turn_04_u", ""},
    	Down = 	{ 007, "Turn_04_d", ""},
 	TiltUp = { 043, "Turn_04_u", ""},
    	TiltDown = { 043, "Turn_04_d", ""},
}

Chord01100 = 
{
	Up = 	{ 008, "Turn_03_u", ""},
    	Down = 	{ 008, "Turn_03_d", ""},
 	TiltUp = { 044, "Turn_03_u", ""},
    	TiltDown = { 044, "Turn_03_d", ""},
}

Chord00110 = 
{
	Up = 	{ 009, "Turn_02_u", ""},
    	Down = 	{ 009, "Turn_02_d", ""},
 	TiltUp = { 045, "Turn_02_u", ""},
	TiltDown = { 045, "Turn_02_d", ""},
}

Chord00011 = 
{
	Up = 	{ 010, "Turn_01_u", ""},
    	Down = 	{ 010, "Turn_01_d", ""},
 	TiltUp = { 046, "Turn_01_u", ""}, 
   	TiltDown = { 046, "Turn_01_d", ""},
}

Chord10100 = 
{
	Up = 	{ 011, "Lick_01_a", ""},
    	Down = 	{ 011, "Lick_01_b", ""},
 	TiltUp = { 047, "Lick_01_a", ""},
    	TiltDown = { 047, "Lick_01_b", ""},
}

Chord01010 = 
{
	Up = 	{ 012, "Scrape_03", ""},
    	Down = 	{ 012, "Lick_02_b", ""},
 	TiltUp = { 048, "Scrape_03", ""},
    	TiltDown = { 048, "Lick_02_b", ""},
}

Chord00101 = 
{
	Up = 	{ 013, "Lick_03_a", ""},
	Down = { 013, "Lick_03_b", ""},
 	TiltUp = { 049, "Lick_03_a", ""},
    	TiltDown = { 049, "Lick_03_b", ""},
}

Chord11100 = 
{
	Up = 	{ 014, "Lick_04_a", ""},
    	Down = 	{ 014, "Lick_09_a", ""},
 	TiltUp = { 050, "Lick_04_a", ""},
    	TiltDown = { 050, "Lick_09_a", ""},
}

Chord01110 = 
{
	Up = 	{ 015, "Lick_05_a", ""},
    	Down = 	{ 015, "Lick_05_b", ""},
 	TiltUp = { 051, "Lick_05_a", ""},
    	TiltDown = { 051, "Lick_05_b", ""},
}

Chord00111 = 
{
	Up = 	{ 016, "Lick_13", ""},
    	Down = 	{ 016, "Lick_06_b", ""},
 	TiltUp = { 052, "Lick_13", ""},
    	TiltDown = { 052, "Lick_06_b", ""},
}

Chord10010 = 
{
	Up = 	{ 017, "Sweep_01_d", "G69"},
	Down = 	{ 017, "Sweep_01_u", "G69"},
 	TiltUp = { 053, "Sweep_01_d", "G69"},
    	TiltDown = { 053, "Sweep_01_u", "G69"},
}

Chord01001 = 
{
	Up = 	{ 018, "Sweep_02_d", "Eminor"},
	Down = 	{ 018, "Sweep_02_u", "Eminor"},
 	TiltUp = { 054, "Sweep_02_d", "Eminor"}, 
   	TiltDown = { 054, "Sweep_02_u", "Eminor"},
}

Chord11110 = 
{
	Up = 	{ 019, "Sweep_03_d", "Dmajor"},
 	Down = 	{ 019, "Sweep_03_u", "Dmajor"},
 	TiltUp = { 055, "Sweep_03_d", "Dmajor"},
    	TiltDown = { 055, "Sweep_03_u", "Dmajor"},
}

Chord01111 = 
{
	Up = 	{ 020, "Sweep_04_d", "A69"},
   	Down = 	{ 020, "Sweep_04_u", "A69"}, 
	TiltUp = { 056, "Sweep_04_d", "A69"},
    	TiltDown = { 056, "Sweep_04_u", "A69"},
}

Chord11010 = 
{
	Up = 	{ 021, "Lick_06_a", ""},
    	Down = 	{ 021, "Lick_06_b", ""},
 	TiltUp = { 057, "Lick_06_a", ""},
    	TiltDown = { 057, "Lick_06_b", ""},
}

Chord10110 = 
{
	Up = 	{ 022, "Lick_07_a", ""},
    	Down = 	{ 022, "Lick_07_b", ""},
 	TiltUp = { 058, "Lick_07_a", ""},
    	TiltDown = { 058, "Lick_07_b", ""},
}

Chord01101 = 
{
	Up = 	{ 023, "Lick_07_c", ""},
    	Down = 	{ 023, "Lick_07_d", ""},
 	TiltUp = { 059, "Lick_07_c", ""},
    	TiltDown = { 059, "Lick_07_d", ""},
}

Chord01011 = 
{
	Up = 	{ 024, "Lick_08_a", ""},
    	Down = 	{ 024, "Lick_08_b", ""},
 	TiltUp = { 060, "Lick_08_a", ""},
    	TiltDown = { 060, "Lick_08_b", ""},
}

Chord10001 = 
{
	Up = 	{ 025, "Squeel_04_u", "E"},
    	Down = 	{ 025, "Squeel_04_d", "E"},
 	TiltUp = { 061, "Squeel_04_u", "E"},
    	TiltDown = { 061, "Squeel_04_d", "E"},
}

Chord11001 = 
{
	Up = 	{ 026, "Lick_10_a", ""},
    	Down = 	{ 026, "Lick_11_a", ""},
 	TiltUp = { 062, "Lick_10_a", ""},
    	TiltDown = { 062, "Lick_11_a", ""},
}

Chord10011 = 
{
	Up = 	{ 027, "TrillEffect_up", ""},
    	Down = 	{ 027, "TrillEffect_down", ""},
 	TiltUp = { 063, "TrillEffect_up", ""},
    	TiltDown = { 063, "TrillEffect_down", ""},
}

Chord11101 = 
{
	Up = 	{ 028, "Whammy_01", ""},
    	Down = 	{ 028, "Whammy_02", ""},
 	TiltUp = { 064, "Whammy_01", ""},
    	TiltDown = { 064, "Whammy_02", ""},
}

Chord10111 = 
{
	Up = 	{ 029, "SillyEffect_up", ""},
    	Down = 	{ 029, "SillyEffect_down", ""},
 	TiltUp = { 065, "SillyEffect_up", ""},
    	TiltDown = { 065, "SillyEffect_down", ""},
}

Chord10101 = 
{
	Up = 	{ 030, "Squeel_03_u", "G"},
    	Down = 	{ 030, "Squeel_03_d", "G"},
 	TiltUp = { 066, "Squeel_03_u", "G"},
    	TiltDown = { 066, "Squeel_03_d", "G"},
}

Chord11011 = 
{
	Up = 	{ 031, "Squeel_02_u", "B"},
    	Down = 	{ 031, "Squeel_02_d", "B"},
 	TiltUp = { 067, "Squeel_02_u", "B"},
    	TiltDown = { 067, "Squeel_02_d", "B"},
}

Chord11111 = 
{
	Up = 	{ 032, "Squeel_01_u", "E"},
    	Down = 	{ 032, "Squeel_01_d", "E"},
 	TiltUp = { 068, "Squeel_01_u", "E"},
    	TiltDown = { 068, "Squeel_01_d", "E"},
}