Chord00000 =
{
	Up = 	{ 000, "Strum_u", ""},
    	Down = 	{ 000, "Strum_d", ""},
 	TiltUp = { 084, "TiltStrum_u", ""},
    	TiltDown = { 084, "TiltStrum_d", ""},
}

Chord10000 = 
{
	Up = 	{ 004, "Note_E1_u", "E"},
	Down = 	{ 004, "Note_E1_d", "E"},
 	TiltUp = { 088, "Tilt_E1_u", "E"},
    	TiltDown = { 088, "Tilt_E1_d", "E"},
}

Chord01000 = 
{
	Up = 	{ 007, "Note_G1_u", "G"},
	Down = 	{ 007, "Note_G1_d", "G"},
 	TiltUp = { 091, "Tilt_G1_u", "G"},
    	TiltDown = { 091, "Tilt_G1_d", "G"},
}

Chord00100 = 
{
	Up = 	{ 009, "Note_A1_u", "A"},
	Down = 	{ 009, "Note_A1_d", "A"},
 	TiltUp = { 093, "Tilt_A1_u", "A"},
    	TiltDown = { 093, "Tilt_A1_d", "A"},
}

Chord00010 = 
{
	Up = 	{ 012, "Note_C2_u", "C"},
	Down = 	{ 012, "Note_C2_d", "C"},
 	TiltUp = { 096, "Tilt_C2_u", "C"},
    	TiltDown = { 096, "Tilt_C2_d", "C"},
}

Chord00001 = 
{
	Up = 	{ 014, "Note_D2_u", "D"},
	Down = 	{ 014, "Note_D2_d", "D"},
 	TiltUp = { 098, "Tilt_D2_u", "D"},
    	TiltDown = { 098, "Tilt_D2_d", "D"},
}

Chord11000 = 
{
	Up = 	{ 005, "Note_F1_u", "F"},
	Down = 	{ 005, "Note_F1_d", "F"},
 	TiltUp = { 089, "Tilt_F1_u", "F"},
    	TiltDown = { 089, "Tilt_F1_d", "F"},
}

Chord01100 = 
{
	Up = 	{ 008, "Note_G#1_u", "G#"},
	Down = 	{ 008, "Note_G#1_d", "G#"},
 	TiltUp = { 092, "Tilt_G#1_u", "G#"},
    	TiltDown = { 092, "Tilt_G#1_d", "G#"},
}

Chord00110 = 
{
	Up = 	{ 010, "Note_A#1_u", "A#"},
	Down = 	{ 010, "Note_A#1_d", "A#"},
 	TiltUp = { 094, "Tilt_A#1_u", "A#"},
    	TiltDown = { 094, "Tilt_A#1_d", "A#"},
}

Chord00011 = 
{
	Up = 	{ 013, "Note_C#2_u", "C#"},
	Down = 	{ 013, "Note_C#2_d", "C#"},
 	TiltUp = { 097, "Tilt_C#2_u", "C#"},
    	TiltDown = { 097, "Tilt_C#2_d", "C#"},
}

Chord10100 = 
{
	Up = 	{ 006, "Note_F#1_u", "F#"},
	Down = 	{ 006, "Note_F#1_d", "F#"},
 	TiltUp = { 090, "Tilt_F#1_u", "F#"},
    	TiltDown = { 090, "Tilt_F#1_d", "F#"},
}

Chord01010 = 
{
	Up = 	{ 011, "Note_B1_u", "B"},
	Down = 	{ 011, "Note_B1_d", "B"},
 	TiltUp = { 095, "Tilt_B1_u", "B"},
    	TiltDown = { 095, "Tilt_B1_d", "B"},
}

Chord00101 = 
{
	Up = 	{ 015, "Note_D#2_u", "D#"},
	Down = 	{ 015, "Note_D#2_d", "D#"},
 	TiltUp = { 099, "Tilt_D#2_u", "D#"},
    	TiltDown = { 099, "Tilt_D#2_d", "D#"},
}

Chord11100 = 
{
	Up = 	{ 016, "Note_E2_u", "E"},
  	Down = 	{ 016, "Note_E2_d", "E"},
 	TiltUp = { 100, "Tilt_E2_u", "E"},
    	TiltDown = { 100, "Tilt_E2_d", "E"},
}

Chord01110 = 
{
	Up = 	{ 019, "Note_G2_u", "G"},
  	Down = 	{ 019, "Note_G2_d", "G"},
 	TiltUp = { 103, "Tilt_G2_u", "G"},
    	TiltDown = { 103, "Tilt_G2_d", "G"},
}

Chord00111 = 
{
	Up = 	{ 021, "Note_A2_u", "A"},
  	Down = 	{ 021, "Note_A2_d", "A"},
 	TiltUp = { 105, "Tilt_A2_u", "A"},
    	TiltDown = { 105, "Tilt_A2_d", "A"},
}

Chord10010 = 
{
	Up = 	{ 018, "Note_F#2_u", "F#"},
	Down = 	{ 018, "Note_F#2_d", "F#"},
 	TiltUp = { 102, "Tilt_F#2_u", "F#"},
    	TiltDown = { 102, "Tilt_F#2_d", "F#"},
}

Chord01001 = 
{
	Up = 	{ 023, "Note_B2_u", "B"},
	Down = 	{ 023, "Note_B2_d", "B"},
 	TiltUp = { 107, "Tilt_B2_u", "B"},
    	TiltDown = { 107, "Tilt_B2_d", "B"},
}

Chord11110 = 
{
	Up = 	{ 024, "Note_C3_u", "C"},
	Down = 	{ 024, "Note_C3_d", "C"},
 	TiltUp = { 108, "Tilt_C3_u", "C"},
    	TiltDown = { 108, "Tilt_C3_d", "C"},
}

Chord01111 = 
{
	Up = 	{ 026, "Note_D3_u", "D"},
	Down = 	{ 026, "Note_D3_d", "D"},
 	TiltUp = { 110, "Tilt_D3_u", "D"},
    	TiltDown = { 110, "Tilt_D3_d", "D"},
}

Chord11010 = 
{
	Up = 	{ 017, "Note_F2_u", "F"},
  	Down = 	{ 017, "Note_F2_d", "F"},
 	TiltUp = { 101, "Tilt_F2_u", "F"},
    	TiltDown = { 101, "Tilt_F2_d", "F"},
}

Chord10110 = 
{
	Up = 	{ 022, "Note_A#2_u", "A#"},
	Down = 	{ 022, "Note_A#2_d", "A#"},
 	TiltUp = { 106, "Tilt_A#2_u", "A#"},
    	TiltDown = { 106, "Tilt_A#2_d", "A#"},
}

Chord01101 = 
{
	Up = 	{ 020, "Note_G#2_u", "G#"},
	Down = 	{ 020, "Note_G#2_d", "G#"},
 	TiltUp = { 104, "Tilt_G#2_u", "G#"},
    	TiltDown = { 104, "Tilt_G#2_d", "G#"},
}

Chord01011 = 
{
	Up = 	{ 025, "Note_C#3_u", "C#"},
	Down = 	{ 025, "Note_C#3_d", "C#"},
 	TiltUp = { 109, "Tilt_C#3_u", "C#"},
    	TiltDown = { 109, "Tilt_C#3_d", "C#"},
}

Chord10001 = 
{
	Up = 	{ 027, "Note_D#3_u", "D#"},
	Down = 	{ 027, "Note_D#3_d", "D#"},
 	TiltUp = { 111, "Tilt_D#3_u", "D#"},
    	TiltDown = { 111, "Tilt_D#3_d", "D#"},
}

Chord11001 = 
{
	Up = 	{ 119, "Fx4_u", ""},
	Down = 	{ 119, "Fx4_d", ""},
 	TiltUp = { 125, "TiltFx4_u", ""},
    	TiltDown = { 125, "TiltFx4_d", ""},
}

Chord10011 = 
{
	Up = 	{ 116, "Fx1_u", ""},
	Down = 	{ 116, "Fx1_d", ""},
 	TiltUp = { 122, "TiltFx1_u", ""},
    	TiltDown = { 122, "TiltFx1_d", ""},
}

Chord11101 = 
{
	Up = 	{ 117, "Fx2_u", ""},
	Down = 	{ 117, "Fx2_d", ""},
 	TiltUp = { 123, "TiltFx2_u", ""},
    	TiltDown = { 123, "TiltFx2_d", ""},
}

Chord10111 = 
{
	Up = 	{ 118, "Fx3_u", ""},
	Down = 	{ 118, "Fx3_d", ""},
 	TiltUp = { 124, "TiltFx3_u", ""},
    	TiltDown = { 124, "TiltFx3_d", ""},
}

Chord10101 = 
{
	Up = 	{ 028, "Note_E3_u", "E"},
	Down = 	{ 028, "Note_E3_d", "E"},
 	TiltUp = { 112, "Tilt_E3_u", "E"},
    	TiltDown = { 112, "Tilt_E3_d", "E"},
}

Chord11011 = 
{
	Up = 	{ 120, "Fx5_u", ""},
	Down = 	{ 120, "Fx5_d", ""},
 	TiltUp = { 126, "TiltFx5_u", ""},
    	TiltDown = { 126, "TiltFx5_d", ""},
}

Chord11111 = 
{
	Up = 	{ 121, "Fx6_u", ""},
	Down = 	{ 121, "Fx6_d", ""},
 	TiltUp = { 127, "TiltFx6_u", ""},
    	TiltDown = { 127, "TiltFx6_d", ""},
}