-------------------------------------------------------------------------------
--
-- Music Rev default character setup Lua.
--
-- Model setups added by Gabs
--
-- Setup Band positional models
--
-------------------------------------------------------------------------------

--require "c0000_bassist_male"
--require "c0000_bassist_female"
--require "c0000_drummer_male"
--require "c0000_drummer_female"
--require "c0000_guitarist_male"
--require "c0000_guitarist_female"
--require "c0000_vocalist_male"
--require "c0000_vocalist_female"

BodyModel = ""

FeModel = ""

HeadModel               	= ""
AttachHeadModel_0       	= ""
AttachHeadModel_1       	= ""
AttachHeadModel_2       	= ""
AttachHeadModel_3       	= ""

PropOneModel            	= ""
AttachPropOneModel_0    	= ""
AttachPropOneModel_1    	= ""
AttachPropOneModel_2    	= ""
AttachPropOneModel_3    	= ""

PropTwoModel            	= ""
AttachPropTwoModel_0    	= ""
AttachPropTwoModel_1    	= ""
AttachPropTwoModel_2    	= ""
AttachPropTwoModel_3    	= ""

PropThreeModel            	= ""
AttachPropThreeModel_0    	= ""
AttachPropThreeModel_1    	= ""
AttachPropThreeModel_2    	= ""
AttachPropThreeModel_3    	= ""

DefaultDrumkitModel     	= 111
DefaultDrumkitSubModel     	= 0
AttachDrumkitModel_0 		= "b_root"
AttachDrumkitModel_1		= ""
AttachDrumkitModel_2		= ""
AttachDrumkitModel_3		= ""

DefaultLeftDrumStickModel   = 101
AttachLeftDrumStickModel_0	= "b_lStick"
AttachLeftDrumStickModel_1	= ""
AttachLeftDrumStickModel_2	= ""
AttachLeftDrumStickModel_3	= ""

DefaultRightDrumStickModel  = 102
AttachRightDrumStickModel_0 = "b_rStick"
AttachRightDrumStickModel_1 = ""
AttachRightDrumStickModel_2 = ""
AttachRightDrumStickModel_3 = ""

DefaultGuitarModel      	= 22
AttachGuitarModel_0 		= "b_guitar"
AttachGuitarModel_1 		= ""
AttachGuitarModel_2 		= ""
AttachGuitarModel_3 		= ""

DefaultBassModel      		= 10
AttachBassModel_0 			= "b_guitar"
AttachBassModel_1 			= ""
AttachBassModel_2 			= ""
AttachBassModel_3 			= ""

DefaultMicstandModel    	= 0
AttachMicstandModel_0 		= "b_micStand"
AttachMicstandModel_1 		= ""
AttachMicstandModel_2 		= ""
AttachMicstandModel_3 		= ""

-------------------------------------------------------------------------------

