-- SKID ROW -- YOUTH GONE WILD KIT --

ListInJamMode = false

-- Audio Mastering information
k1005 = 
{	
	ParentMix = "MusicMix001",
	MixType = 2,		
	Volume = 0,	
	DSPs = { "Compressor1005" }
}

Compressor1005 = 
{ 
	MixType = 3,
	EffectType = 17,
	EffectParam001 = { "Threshold", -12.41 },
	EffectParam002 = { "Attack", 42.74 },
	EffectParam003 = { "Release", 70.4 },		
	EffectParam004 = { "Gain", 9.65 }	
}
