-- ALL AMERICAN  REJECTS -- DIRTY LITTLE SECRET KIT --

ListInJamMode = false

-- Audio Mastering information
k1012 = 
{	
	ParentMix = "MusicMix001",
	MixType = 2,		
	Volume = 0,	
	DSPs = { "Compressor1012" }
}

Compressor1012 = 
{ 
	MixType = 3,
	EffectType = 17,
	EffectParam001 = { "Threshold", -13.10 },
	EffectParam002 = { "Attack", 27.44 },
	EffectParam003 = { "Release", 70.46 },		
	EffectParam004 = { "Gain", 8.28 }	
}
