-- MEGADETH -- HOLY WARS... THE PUNISHMENT -- HOLY WARS KIT

ListInJamMode = false

-- Audio Mastering information
k1028 = 
{	
	ParentMix = "MusicMix001",
	MixType = 2,		
	Volume = 0,	
	DSPs = { "Compressor1028" }
}

Compressor1028 = 
{ 
	MixType = 3,
	EffectType = 17,
	EffectParam001 = { "Threshold", -17.24 },
	EffectParam002 = { "Attack", 40.5 },
	EffectParam003 = { "Release", 70.4 },		
	EffectParam004 = { "Gain", 11.03 }	
}
