-- IRON MAIDEN -- RUN TO THE HILLS KIT --

ListInJamMode = false

-- Audio Mastering information
k1037 = 
{	
	ParentMix = "MusicMix001",
	MixType = 2,		
	Volume = 0,	
	DSPs = { "Compressor1037" }
}

Compressor1037 = 
{ 
	MixType = 3,
	EffectType = 17,
	EffectParam001 = { "Threshold", -9.65 },
	EffectParam002 = { "Attack", 23.11 },
	EffectParam003 = { "Release", 143.4 },		
	EffectParam004 = { "Gain", 9.15 }	
}
