-- SOUND GARDEN -- SPOONMAN --

ListInJamMode = false

-- Audio Mastering information
k1034 = 
{	
	ParentMix = "MusicMix001",
	MixType = 2,		
	Volume = 0,	
	DSPs = { "Compressor1034" }
}

Compressor1034 = 
{ 
	MixType = 3,
	EffectType = 17,
	EffectParam001 = { "Threshold", -13.79 },
	EffectParam002 = { "Attack", 28.5 },
	EffectParam003 = { "Release", 70.4 },		
	EffectParam004 = { "Gain", 12.23 }	
}
