-- THE KILLERS -- SOMEBODY TOLD ME KIT --

ListInJamMode = false

-- Audio Mastering information
k1033 = 
{	
	ParentMix = "MusicMix001",
	MixType = 2,		
	Volume = 0,	
	DSPs = { "Compressor1033" }
}

Compressor1033 = 
{ 
	MixType = 3,
	EffectType = 17,
	EffectParam001 = { "Threshold", -15.17 },
	EffectParam002 = { "Attack", 28.5 },
	EffectParam003 = { "Release", 70.4 },		
	EffectParam004 = { "Gain", 8.30 }	
}
