-- KILLSWITCH ENGAGE -- END OF HEARTACHE KIT --

ListInJamMode = false

-- Audio Mastering information
k1041 = 
{	
	ParentMix = "MusicMix001",
	MixType = 2,		
	Volume = 0,	
	DSPs = { "Compressor1041" }
}

Compressor1041 = 
{ 
	MixType = 3,
	EffectType = 17,
	EffectParam001 = { "Threshold", -15.86 },
	EffectParam002 = { "Attack", 25.4 },
	EffectParam003 = { "Release", 70.4 },		 
	EffectParam004 = { "Gain", 8.62 }	
}
