-- SYSTEM OF A DOWN -- CHOP SUEY KIT! --

ListInJamMode = false

-- Audio Mastering information
k1046 = 
{	
	ParentMix = "MusicMix001",
	MixType = 2,		
	Volume = 0,	
	DSPs = { "Compressor1046" }
}

Compressor1046 = 
{ 
	MixType = 3,
	EffectType = 17,
	EffectParam001 = { "Threshold", -14.48 },
	EffectParam002 = { "Attack", 41.6 },
	EffectParam003 = { "Release", 132.4 },		 
	EffectParam004 = { "Gain", 9.07 }	
}
