-- JET -- ARE YOU GONNA BE MY GIRL KIT --

ListInJamMode = false

-- Audio Mastering information
k1049 = 
{	
	ParentMix = "MusicMix001",
	MixType = 2,		
	Volume = 0,	
	DSPs = { "Compressor1049" }
}

Compressor1049 = 
{ 
	MixType = 3,
	EffectType = 17,
	EffectParam001 = { "Threshold", -11.72 },
	EffectParam002 = { "Attack", 25.4 },
	EffectParam003 = { "Release", 70.4 },		 
	EffectParam004 = { "Gain", 6.21 }	
}
