-- SCORPIONS -- NO ONE LIKE YOU KIT --

ListInJamMode = false

-- Audio Mastering information
k1043 = 
{	
	ParentMix = "MusicMix001",
	MixType = 2,		
	Volume = 0,	
	DSPs = { "Compressor1043" }
}

Compressor1043 = 
{ 
	MixType = 3,
	EffectType = 17,
	EffectParam001 = { "Threshold", -11.41 },
	EffectParam002 = { "Attack", 29.6 },
	EffectParam003 = { "Release", 110.4 },		 
	EffectParam004 = { "Gain", 5.82 }	
}
