-- FALL OUT BOY -- DANCE, DANCE KIT --

ListInJamMode = false

-- Audio Mastering information
k1009 = 
{	
	ParentMix = "MusicMix001",
	MixType = 2,		
	Volume = 0,	
	DSPs = { "Compressor1009" }
}

Compressor1009 = 
{ 
	MixType = 3,
	EffectType = 17,
	EffectParam001 = { "Threshold", -8.89 },
	EffectParam002 = { "Attack", 40.74 },
	EffectParam003 = { "Release", 132.4 },		
	EffectParam004 = { "Gain", 8.09 }	
}
