-- BLINK 182 -- ALL THE SMALL THINGS -- SKATE KIT --

ListInJamMode = false

-- Audio Mastering information
k1004 = 
{	
	ParentMix = "MusicMix001",
	MixType = 2,		
	Volume = 0,	
	DSPs = { "Compressor1004" }
}

Compressor1004 = 
{ 
	MixType = 3,
	EffectType = 17,
	EffectParam001 = { "Threshold", -11.72 },
	EffectParam002 = { "Attack", 18.74 },
	EffectParam003 = { "Release", 70.4 },		
	EffectParam004 = { "Gain", 13.5 }	
}
