-- DREAM THEATRE -- PULL ME UNDER KIT --

ListInJamMode = false

-- Audio Mastering information
k1015 = 
{	
	ParentMix = "MusicMix001",
	MixType = 2,		
	Volume = 0,	
	DSPs = { "Compressor1015" }
}

Compressor1015 = 
{ 
	MixType = 3,
	EffectType = 17,
	EffectParam001 = { "Threshold", -12.26 },
	EffectParam002 = { "Attack", 25.44 },
	EffectParam003 = { "Release", 70.4 },		
	EffectParam004 = { "Gain", 8.47 }	
}
