-- CREAM -- WHITE ROOM -- VINTAGE ROOM KIT --

ListInJamMode = false

-- Audio Mastering information
k1018 = 
{	
	ParentMix = "MusicMix001",
	MixType = 2,		
	Volume = 0,	
	DSPs = { "Compressor1018" }
}

Compressor1018 = 
{ 
	MixType = 3,
	EffectType = 17,
	EffectParam001 = { "Threshold", -15.86 },
	EffectParam002 = { "Attack", 25.44 },
	EffectParam003 = { "Release", 70.4 },		
	EffectParam004 = { "Gain", 9.68 }	
}
