-- QUEEN -- STONE COLD CRAZY -- STONE COLD KIT --

ListInJamMode = false

-- Audio Mastering information
k1016 = 
{	
	ParentMix = "MusicMix001",
	MixType = 2,		
	Volume = 0,	
	DSPs = { "Compressor1016" }
}

Compressor1016 = 
{ 
	MixType = 3,
	EffectType = 17,
	EffectParam001 = { "Threshold", -13.79 },
	EffectParam002 = { "Attack", 25.44 },
	EffectParam003 = { "Release", 70.4 },		
	EffectParam004 = { "Gain", 9.86 }	
}
