-- DEEP PURPLE -- HIGHWAY STAR -- VINTAGE PURPLE KIT

ListInJamMode = false

-- Audio Mastering information
k1014 = 
{	
	ParentMix = "MusicMix001",
	MixType = 2,		
	Volume = 0,	
	DSPs = { "Compressor1014" }
}

Compressor1014 = 
{ 
	MixType = 3,
	EffectType = 17,
	EffectParam001 = { "Threshold", -11.72 },
	EffectParam002 = { "Attack", 25.74 },
	EffectParam003 = { "Release", 256.4 },		
	EffectParam004 = { "Gain", 7.21 }	
}
