-- QUIET RIOT -- CUM ON FEEL THE NOISE KIT --

ListInJamMode = false

-- Audio Mastering information
k1017 = 
{	
	ParentMix = "MusicMix001",
	MixType = 2,		
	Volume = 0,	
	DSPs = { "Compressor1017" }
}

Compressor1017 = 
{ 
	MixType = 3,
	EffectType = 17,
	EffectParam001 = { "Threshold", -9.65 },
	EffectParam002 = { "Attack", 25.44 },
	EffectParam003 = { "Release", 70.4 },		
	EffectParam004 = { "Gain", 4.83 }	
}
