-- JUDAS PRIEST -- HEAD OUT TO THE HIGHWAY --

ListInJamMode = false

-- Audio Mastering information
k1027 = 
{	
	ParentMix = "MusicMix001",
	MixType = 2,		
	Volume = 0,	
	DSPs = { "Compressor1027" }
}

Compressor1027 = 
{ 
	MixType = 3,
	EffectType = 17,
	EffectParam001 = { "Threshold", -17.24 },
	EffectParam002 = { "Attack", 40.5 },
	EffectParam003 = { "Release", 70.4 },		
	EffectParam004 = { "Gain", 6.73 }	
}
