-- WHITESNAKE -- STILL OF THE NIGHT -- GLAM KIT --

ListInJamMode = false

-- Audio Mastering information
k1035 = 
{	
	ParentMix = "MusicMix001",
	MixType = 2,		
	Volume = 0,	
	DSPs = { "Compressor1035" }
}

Compressor1035 = 
{ 
	MixType = 3,
	EffectType = 17,
	EffectParam001 = { "Threshold", -10.34 },
	EffectParam002 = { "Attack", 39.3 },
	EffectParam003 = { "Release", 70.4 },		
	EffectParam004 = { "Gain", 5.17 }	
}
