-- PANTERA -- WALK KIT --

ListInJamMode = false

-- Audio Mastering information
k1038 = 
{	
	ParentMix = "MusicMix001",
	MixType = 2,		
	Volume = 0,	
	DSPs = { "Compressor1038" }
}

Compressor1038 = 
{ 
	MixType = 3,
	EffectType = 17,
	EffectParam001 = { "Threshold", -15.86 },
	EffectParam002 = { "Attack", 25.11 },
	EffectParam003 = { "Release", 70.46 },		
	EffectParam004 = { "Gain", 6.10 }	
}
