-- THE WHO -- WON'T GET FOOLED AGAIN KIT -- 

ListInJamMode = false

-- Audio Mastering information
k1036 = 
{	
	ParentMix = "MusicMix001",
	MixType = 2,		
	Volume = 0,	
	DSPs = { "Compressor1036" }
}

Compressor1036 = 
{ 
	MixType = 3,
	EffectType = 17,
	EffectParam001 = { "Threshold", -9.65 },
	EffectParam002 = { "Attack", 23.11 },
	EffectParam003 = { "Release", 290.4 },		
	EffectParam004 = { "Gain", 9.20 }	
}
