-- THREE DAYS GRACE -- PAIN -- NU-METAL KIT --

ListInJamMode = false

-- Audio Mastering information
k1039 = 
{	
	ParentMix = "MusicMix001",
	MixType = 2,		
	Volume = 0,	
	DSPs = { "Compressor1039" }
}

Compressor1039 = 
{ 
	MixType = 3,
	EffectType = 17,
	EffectParam001 = { "Threshold", -16.55 },
	EffectParam002 = { "Attack", 42.07 },
	EffectParam003 = { "Release", 121.2 },		 
	EffectParam004 = { "Gain", 9.10 }	
}
