-- FOO FIGHTERS -- ALL MY LIFE KIT --

ListInJamMode = false

-- Audio Mastering information
k1047 = 
{	
	ParentMix = "MusicMix001",
	MixType = 2,		
	Volume = 0,	
	DSPs = { "Compressor1047" }
}

Compressor1047 = 
{ 
	MixType = 3,
	EffectType = 17,
	EffectParam001 = { "Threshold", -11.03 },
	EffectParam002 = { "Attack", 25.4 },
	EffectParam003 = { "Release", 70.4 },		 
	EffectParam004 = { "Gain", 4.26 }	
}
