-- LITA FORD -- KISS ME DEADLY KIT --

ListInJamMode = false

-- Audio Mastering information
k1058 = 
{	
	ParentMix = "MusicMix001",
	MixType = 2,		
	Volume = 0,	
	DSPs = { "Compressor1058" }
}

Compressor1058 = 
{ 
	MixType = 3,
	EffectType = 17,
	EffectParam001 = { "Threshold", -11.72 },
	EffectParam002 = { "Attack", 25.4 },
	EffectParam003 = { "Release", 70.4 },		 
	EffectParam004 = { "Gain", 8.03 }	
}
