-- AVRIL LAVIGNE -- SK8ER BOI KIT --

ListInJamMode = false

-- Audio Mastering information
k1059 = 
{	
	ParentMix = "MusicMix001",
	MixType = 2,		
	Volume = 0,	
	DSPs = { "Compressor1059" }
}

Compressor1059 = 
{ 
	MixType = 3,
	EffectType = 17,
	EffectParam001 = { "Threshold", -13.11 },
	EffectParam002 = { "Attack", 25.4 },
	EffectParam003 = { "Release", 70.4 },		 
	EffectParam004 = { "Gain", 6.81 }	
}
