-- JOAN JETT -- BAD REPUTATION KIT --

ListInJamMode = false

-- Audio Mastering information
k1057 = 
{	
	ParentMix = "MusicMix001",
	MixType = 2,		
	Volume = 0,	
	DSPs = { "Compressor1057" }
}

Compressor1057 = 
{ 
	MixType = 3,
	EffectType = 17,
	EffectParam001 = { "Threshold", -14.48 },
	EffectParam002 = { "Attack", 25.4 },
	EffectParam003 = { "Release", 70.4 },		 
	EffectParam004 = { "Gain", 7.13 }	
}
