

--Created in MoonApp/Main.cpp...Geo order as from the dae...before it is sorted by Moon



--Load the geos in the order of 

PreSortOrder = 
{
	"h0001_5091_targetBackgroundExtended_p1_0000",
	"h0001_5062_targetBackSlash_p1_0000",
	"h0001_5061_targetNumber_p1_0000",
	"h0001_5061_targetNumber_p1_0001",
	"h0001_5061_targetNumber_p1_0002",
	"h0001_5061_hitNumber_p1_0000",
	"h0001_5061_hitNumber_p1_0001",
	"h0001_5061_hitNumber_p1_0002",
}
PostSortOrder = 
{
	h0001_5061_targetNumber_p1_0000 = { 	 modelIndex = 0, 	 instanceIndex = -1},
	h0001_5061_targetNumber_p1_0001 = { 	 modelIndex = 0, 	 instanceIndex = 0},
	h0001_5061_targetNumber_p1_0002 = { 	 modelIndex = 0, 	 instanceIndex = 1},
	h0001_5061_hitNumber_p1_0000 = { 	 modelIndex = 0, 	 instanceIndex = 2},
	h0001_5061_hitNumber_p1_0001 = { 	 modelIndex = 0, 	 instanceIndex = 3},
	h0001_5061_hitNumber_p1_0002 = { 	 modelIndex = 0, 	 instanceIndex = 4},
	h0001_5062_targetBackSlash_p1_0000 = { 	 modelIndex = 1, 	 instanceIndex = -1},
	h0001_5091_targetBackgroundExtended_p1_0000 = { 	 modelIndex = 2, 	 instanceIndex = -1},
}
